parameters:
#    ingetis_menu.example.class: Ingetis\MenuBundle\Example

services:
#    ingetis_menu.example:
#        class: %ingetis_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
