parameters:
#    ingetis_carousel.example.class: Ingetis\CarouselBundle\Example

services:
#    ingetis_carousel.example:
#        class: %ingetis_carousel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
