ingetis_user:
    resource: "@IngetisUserBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_div_index:
    resource: "@IngetisDivIndexBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_annonce_index:
    resource: "@IngetisAnnonceIndexBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_menu:
    resource: "@IngetisMenuBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_pages:
    resource: "@IngetisPagesBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_offres:
    resource: "@IngetisOffresBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_navbar:
    resource: "@IngetisNavbarBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_index:
    resource: "@IngetisIndexBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_carousel:
    resource: "@IngetisCarouselBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_news:
    resource: "@IngetisNewsBundle/Resources/config/routing.yml"
    prefix:   /

ingetis_site:
    resource: "@IngetisSiteBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
