parameters:
#    ingetis_annonce_index.example.class: Ingetis\AnnonceIndexBundle\Example

services:
#    ingetis_annonce_index.example:
#        class: %ingetis_annonce_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
