parameters:
#    ingetis_offres.example.class: Ingetis\OffresBundle\Example

services:
#    ingetis_offres.example:
#        class: %ingetis_offres.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
