parameters:
#    ingetis_pages.example.class: Ingetis\PagesBundle\Example

services:
#    ingetis_pages.example:
#        class: %ingetis_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
