parameters:
#    ingetis_site.example.class: Ingetis\SiteBundle\Example

services:
#    ingetis_site.example:
#        class: %ingetis_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
