parameters:
#    ingetis_index.example.class: Ingetis\IndexBundle\Example

services:
#    ingetis_index.example:
#        class: %ingetis_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
